# Generated by Django 4.1.2 on 2022-11-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_room_topic_delete_message_delete_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
