# Generated by Django 4.1.3 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=30, null=True)),
                ('name', models.CharField(default=None, max_length=150, null=True)),
                ('sectorName', models.CharField(default=None, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Stock_Companies',
                'ordering': ['symbol'],
            },
        ),
    ]
